{% set name = "jsonapi-requests" %}
{% set version = "0.6.0" %}
{% set sha256 = "b15a4c9a4d5d04d8c5913fd2f5f808b36d52686372aba36726113e7444118c74" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"


requirements:
  host:
    - python
    - pip
    - pytest-runner
    - setuptools
  run:
    - python
    - requests
    - tenacity

test:
  imports:
    - jsonapi_requests
    - jsonapi_requests.orm

about:
  home: https://github.com/socialwifi/jsonapi-requests
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python client implementation for JSON API 1.0'

  doc_url: https://github.com/socialwifi/jsonapi-requests/wiki
  dev_url: https://github.com/socialwifi/jsonapi-requests

extra:
  recipe-maintainers:
    - sodre
