{% set name = "jsonapi-requests" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: baacf281d831debeb7233e9cd88936f3bf8b681d6c1948e7c508ad2f403e55ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - pytest-runner
  run:
    - python >=3
    - requests
    - tenacity

test:
  imports:
    - jsonapi_requests
    - jsonapi_requests.orm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/socialwifi/jsonapi-requests
  summary: Python client implementation for json api. http://jsonapi.org/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

  doc_url: https://github.com/socialwifi/jsonapi-requests/wiki
  dev_url: https://github.com/socialwifi/jsonapi-requests

extra:
  recipe-maintainers:
    - sodre
