{% set name = "jsonapi-requests" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jsonapi-requests-{{ version }}.tar.gz
  sha256: fe09b53372fdc7ee183aafb98baac04c4b7c81c1def1f6725596f16c8af0bd92

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - pytest-runner
  run:
    - python >=3
    - requests
    - tenacity

test:
  imports:
    - jsonapi_requests
    - jsonapi_requests.orm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/socialwifi/jsonapi-requests
  summary: Python client implementation for json api. http://jsonapi.org/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

  doc_url: https://github.com/socialwifi/jsonapi-requests/wiki
  dev_url: https://github.com/socialwifi/jsonapi-requests

extra:
  recipe-maintainers:
    - sodre
