{% set name = "jsonapi-requests" %}
{% set version = "0.6.2" %}
{% set sha256 = "ce83161f0e1d5007ec55a4083563f5e726e052e382fd05c42e6c0115bd9dc650" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps .

requirements:
  host:
    - python >=3
    - pip
    - pytest-runner
    - setuptools
  run:
    - python >=3
    - requests
    - tenacity

test:
  requires:
    - pip
  imports:
    - jsonapi_requests
    - jsonapi_requests.orm
  commands:
    - pip check

about:
  home: https://github.com/socialwifi/jsonapi-requests
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python client implementation for JSON API 1.0

  doc_url: https://github.com/socialwifi/jsonapi-requests/wiki
  dev_url: https://github.com/socialwifi/jsonapi-requests

extra:
  recipe-maintainers:
    - sodre
