appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: JEi5806mtlIt8R+z84WbeZnaFHhk1r5on9mBP5Un+k8OJFybcgAy3SqaDBzVr84MW4mRmTWhk+Xc+uhle3phrShTosvr+5d3nojbck1RpHVczIuBfaXhhHSTkorDBhpf3A9PxzhhwpsNvKpl6RYl9GDppw4ko3mFWzOFEOiKccLif5Xok0Bu4ShGHARm6jrvR8G1SXrAMKGI+V4NMYjLgnEFVhePTrfInQ0YFYI54C7PWfENqo4Ncm7kqUkMMNw3rZkV05q6ok9WIUNDa0krYA4R5BVWvx3hnGzzN8PtUsXr+YTFLF3LR2jwq3e8R3COZUZ8465NpNpUEBcLPbEJktMGJKDFGbaqR5mDquf1+dZZmkt43R3cop8Ookey601Oy01awEKMy2M+U9HekMLyDu3sIyP37ETzNjRuoxINoM6UyWDU5nE+TJg2kDMl6Gn243vwJJwZFjiotazFz5mOV8SkAqQ9eANCr+yQuDu2JZw+BUId3CxqgKyMk9HsidovVza3FfiLEG+dAl6Fp4tKV6Os06ZhciI/T35p1CQcoCN7cE8nlkM5QJ5ExZBkFPWjrcsF/pBTSHyXg08KjkrmS3htC/JNw2x+zgALmWlq37j4sPO1nQDYug5oRE1ws6q3Wq36fkgpMPA4HZt0UH2WhEfyVESANDXoyrstcTepYH0=}
